name: Build App for Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Install Dependencies
      run: npm install

    - name: Build App for Windows
      run: npm run tauri build

    - name: Log
      run: "pwd"

    - name: Upload Tauri Build
      uses: actions/upload-artifact@v2
      with:
        name: tauri-build
        path: src-tauri/target

      # run: npm run tauri build --target win

    #- uses: tauri-apps/tauri-action@v0
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Upload Artifacts
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: tauri-build
    #    path: target/tauri-app-win
